import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:cloud_firestore/cloud_firestore.dart';
import '../model/payment_model.dart';
import '../model/water_usage_model.dart';

class MpesaService {
  // ✅ Node server URL configuration
  static const String _baseUrl =
      'http://10.10.226.251:5000'; // change as per the ip of your computer

  /// Get the appropriate base URL based on environment
  static String get baseUrl {
    return _baseUrl;
  }

  /// Initiates M-Pesa STK Push payment
  static Future<String?> initiatePayment({
    required String userId,
    required String phone,
    required double amount,
    required String accountRef,
  }) async {
    try {
      print('🔄 Initiating payment to: $baseUrl/mpesa/stkpush');
      print(
          '📱 User: $userId, Phone: $phone, Amount: $amount, Account: $accountRef');

      final response = await http
          .post(
            Uri.parse('$baseUrl/mpesa/stkpush'),
            headers: {
              'Content-Type': 'application/json',
              'Accept': 'application/json',
            },
            body: json.encode({
              'userId': userId,
              'phoneNumber': phone,
              'amount': amount,
              'accountRef': accountRef,
            }),
          )
          .timeout(const Duration(seconds: 30));

      print('📡 Response status: ${response.statusCode}');
      print('📡 Response body: ${response.body}');

      if (response.statusCode == 200) {
        final data = json.decode(response.body);

        if (data['success'] == true) {
          await savePaymentToFirestore(
            userId: userId,
            phone: phone,
            amount: amount,
            accountRef: accountRef,
            status: 'Pending',
            transactionId: data['CheckoutRequestID'] ?? '',
          );

          return data['CustomerMessage'] ?? 'Payment initiated successfully';
        } else {
          throw Exception(data['error'] ?? 'Payment failed');
        }
      } else {
        final data = json.decode(response.body);
        throw Exception(data['error'] ?? 'HTTP error: ${response.statusCode}');
      }
    } on http.ClientException catch (e) {
      print('❌ HTTP Client Exception: $e');
      throw Exception(
          'Network error: Cannot connect to server. Please check if server is running.');
    } on FormatException catch (e) {
      print('❌ JSON Format Exception: $e');
      throw Exception('Invalid server response');
    } on Exception catch (e) {
      print('❌ General Exception: $e');
      rethrow;
    }
  }

  /// Saves the payment transaction to Firestore using Payment model
  static Future<void> savePaymentToFirestore({
    required String userId,
    required String phone,
    required double amount,
    required String accountRef,
    required String status,
    String? transactionId,
  }) async {
    try {
      final payment = Payment(
        id: '', // Will be generated by Firestore
        userId: userId,
        phone: phone,
        amount: amount,
        accountRef: accountRef,
        status: status,
        transactionId: transactionId ?? '',
        timestamp: DateTime.now(),
        unitsPurchased: 0,
        processed: false,
      );

      await FirebaseFirestore.instance
          .collection('payments')
          .add(payment.toMap());

      print('✅ Payment saved to Firestore with status: $status');
    } catch (e) {
      print('❌ Error saving payment: $e');
      rethrow;
    }
  }

  /// Get water usage as WaterUsage model - UPDATED
  static Future<WaterUsage?> getWaterUsage(String meterNumber) async {
    try {
      final doc = await FirebaseFirestore.instance
          .collection('waterUsage')
          .doc(meterNumber)
          .get();

      if (doc.exists) {
        return WaterUsage.fromFirestore(doc);
      }
      return null;
    } catch (e) {
      print('❌ Error fetching water usage: $e');
      return null;
    }
  }

  /// Get payment history as List<Payment> - UPDATED
  static Future<List<Payment>> getPaymentHistory(String meterNumber) async {
    try {
      final querySnapshot = await FirebaseFirestore.instance
          .collection('payments')
          .where('accountRef', isEqualTo: meterNumber)
          .orderBy('timestamp', descending: true)
          .limit(10)
          .get();

      return querySnapshot.docs
          .map((doc) => Payment.fromFirestore(doc))
          .toList();
    } catch (e) {
      print('❌ Error fetching payment history: $e');
      return [];
    }
  }

  /// Get real-time water usage stream
  static Stream<WaterUsage?> getWaterUsageStream(String meterNumber) {
    return FirebaseFirestore.instance
        .collection('waterUsage')
        .doc(meterNumber)
        .snapshots()
        .map((doc) => doc.exists ? WaterUsage.fromFirestore(doc) : null);
  }

  /// Get real-time payment history stream
  static Stream<List<Payment>> getPaymentHistoryStream(String meterNumber) {
    return FirebaseFirestore.instance
        .collection('payments')
        .where('accountRef', isEqualTo: meterNumber)
        .orderBy('timestamp', descending: true)
        .limit(10)
        .snapshots()
        .map((querySnapshot) => querySnapshot.docs
            .map((doc) => Payment.fromFirestore(doc))
            .toList());
  }

  /// Test connection to the server
  static Future<bool> testConnection() async {
    try {
      final response = await http
          .get(Uri.parse('$baseUrl/test'))
          .timeout(const Duration(seconds: 10));
      print('🔗 Server test response: ${response.statusCode}');
      return response.statusCode == 200;
    } catch (e) {
      print('❌ Server connection test failed: $e');
      return false;
    }
  }
}
