import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <-- Make sure this file exists (generated by FlutterFire CLI)
import 'package:smartpay/screens/login.dart';
import 'package:smartpay/screens/signup.dart';
import 'package:smartpay/screens/dashboard.dart';
import 'package:smartpay/screens/viewreport.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // firebase initializations
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SmartPay',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      // routes to specificant files
      initialRoute: '/signup',
      routes: {
        '/signup': (context) => const SignUpScreen(),
        '/login': (context) => const LoginScreen(),
        '/dashboard': (context) => const Dashboard(),
        '/viewreport': (context) => const ViewReport(),
      },
    );
  }
}
